### ISSUE TITLE
CSGO React HUD doesn't work after newest update

### ISSUE THREAD

**Issue by vepth** [lexogrine/csgo-react-hud#33]
Greetings Lexogrine!

I've been using my edited version of CSGO React HUD in Lexogrine HUD manager with my team for awhile, and it's been working like a charm. Today I tried to change couple of things in the HUD but when I did `npm start`, it started with no errors but didn't show in Lexogrine HUD manager HUDs tab at all.

So I cloned newest version of this React HUD. After successful `npm install`, I started HUD with `npm start` and it started with no errors, with message pasted bellow.

```
PS C:\Users\User\Desktop\csgo-react-hud> npm start

> lexogrine_hud@1.9.0 start C:\Users\User\Desktop\csgo-react-hud
> craco start

Compiled successfully!

You can now view lexogrine_hud in the browser.

  Local:            http://localhost:3500/dev
  On Your Network:  http://192.168.1.7:3500/dev

Note that the development build is not optimized.
To create a production build, use yarn build.
```

When HUD showed up in Lexogrine HUD manager named *[DEV] Lexogrine HUD*, I opened it in browser and nothing, just a white screen. When I run the HUD as an instance of Lexogrine HUD manager, nothing shows up, not even a Lexogrine watermark. I've tried both running CSGO itself and running test data, nothing works.

--------

I tried to inspect the page, and `<iframe>` that should have the HUD itself is empty (source code of the page [here](https://pastebin.com/KjaguAjK)).

Tag src links to `src="/dev/?port=1349"`. When I visit that page, I get this error
```
{"expected":["http://192.168.1.7:1349/dev","http://***.**.***.**:1349/dev"]} // Numbers with * are my public IP address
```

On the other side, when I download [latest release](https://github.com/lexogrine/csgo-react-hud/releases) of this HUD, it works just fine.

--------

### What I've done:

- [x] Updated to the latest version of Lexogrine HUD manager v1.10.0
- [x] Cloned latest version of CSGO React HUD v1.9.0
- [x] Installed Node.js and npm modules
- [x] Added Steam API key in Lexogrine HUD Manager
- [x] Loaded CGI file
- [x] Loaded Configs
- [x] Added two teams and a Live match between them

**Comment by gospod-srb** [comment]
I have tested a bit more and seems like that even while using compiled [newest release](https://github.com/lexogrine/csgo-react-hud/releases) on the newest version of Lexogrine HUD Manager, HUD doesn't show up when running it as an instance of the manager (as an overlay), but it works fine in browser.

----
As you can see from the image below, on the left side of the screen is working React HUD, on the right side is opened HUD manager and in taskbar preview there is no HUD, not even a watermark. 

![Image of HUD not working](https://i.imgur.com/5TAtMTF.png)

Same thing happens when I use my custom version of HUD that is couple of versions old:

![Image of my HUD not working](https://i.imgur.com/mmEkAU6.png)

**Comment by osztenkurden** [comment]
@gospod-srb I can't replicate it on my end on any of the 3 pcs i have access to. Can I contact you somehow (email or discord prefferably) so we can set up a debugging session?

**Comment by gospod-srb** [comment]
> @gospod-srb I can't replicate it on my end on any of the 3 pcs i have access to. Can I contact you somehow (email or discord prefferably) so we can set up a debugging session?

Of course, you can contact me via Discord 𝙂 𝙤 𝙨 𝙥 𝙤 𝘿 #6335
